Repository takeshape/.github, pull requests merged in 2020-08, with the labels that each got.

#3 adding descriptions to points
  labels/labels.yml
Labels: type: documentation ✏️

#11 Update README.md
  README.md
Labels: type: bug 🐛

#15 Update README.md
  README.md
Labels: type: feature 🔨

#16 adding more detail to workflow sync section
  README.md
Labels: type: chore 🧺

#18 fixing a fake bug
  README.md
Labels: type: bug 🐛

#21 Removing cruft from readme
  README.md
Labels: type: documentation ✏️

#23 Update README.md
  README.md
Labels: type: chore 🧺

#28 add labels for codetree
  labels/labels.yml
Labels: type: chore 🧺
